Voting
rublen/qna pull request #9
Opened 2018-10-31 20:21 UTC by rublen

2018-11-01 09:02 UTC, vkurennov requested changes

2018-11-01 09:02 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +  var voteUp = document.querySelector('.vote-up');
Вот тут закрадываются сомнения, зачем тебе один самый первый элемент? Ведь они у тебя и так в voteUps лежат. Можно оттуда взять по индексу, либо, что лучше, здесь сделать более конкретный селектор. Я пердполагаю, что это рейтинг вопроса, может выбрать элемент как-то вроде `.question .vote-up`

2018-11-01 09:02 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +      votes = JSON.parse(event.detail[2].responseText).votable_sum;
если взять из detail элемент с индексом 0 или 1, то там уже будет распарсенный json и не нужно будет его каждый раз парсить (тебя, кстати, не смутило, что ты один и тот же текст парсишь 4 раза ;)?)

2018-11-01 09:02 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +      if (upVoted == true) {
Сравнивать логические элементы с true/false не принято, потому что запись `if (upVoted)` это то же самое, а для false будет `if (!upVoted)`

2018-11-01 09:02 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +      } else { if (downVoted == false) {
в конструкии else if фигурная скобка перед if не ставится и см. мой комментарий выше - замени на отрицание.

2018-11-01 09:02 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +  voteDowns.forEach(function(voteDown) {
См. комментарии выше

2018-11-01 09:02 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      vote_id: vote.id,
одного id маловато. У тебя может быть вопрос с id 1 и ответ с таким же id на той же старнице. За какой объект в этом случае подан голос? И это надо учесть и в скриптах, т.к. явно одного только id для поиска элемента не достаточно будет.

2018-11-01 09:02 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      votes.where(user: user)[0]
Индексы в таких конструкциях очень некрасиво выглядят. Используй метод `first`.

2018-11-01 09:02 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    def vote(user)
Метод лучше назвать vote_by, чтобы было ясно, что возвращается голос, т.к. названием  vote может ввести в заблуждение: можно подумать, что это метод голосования от имени пользователя (т.е. команда)

2018-11-01 09:02 UTC, vkurennov commented on app/views/votes/_voting.html.slim
> +  - elsif votable.downvoted?(current_user)
Здесь отличие от блока в if только в некоторых классах и в цвете у первой ссылки. Так стоит ли дублировать остальные 90%, которые не меняются?

2018-11-01 09:02 UTC, vkurennov commented on app/views/votes/_voting.html.slim
> +.vote-down
в этом блоке тоже можно сократить код, избавившись от лишнего дублирования и вынеся под условия только изменяемые части.

2018-11-01 09:02 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +module Voted
Большого смысла делать здесь консерн не было, т.к. он все равно в один контроллер включается. А методы, которые в  included должны быть приватными, т.к. это не экшены. В контроллерах публичными должны быть только методы-экшены, т.е. те, которые вызываются в ответ на запросы.

2018-11-01 09:02 UTC, vkurennov commented on spec/acceptance/best_answer_for_question_spec.rb
>          within(all(".row").first) { expect(page).to have_content("#{answer_2}") }
По аккуратнее с привязкой к верстке, она может поменяться, при этом тесты посыпятся.

2018-11-01 09:02 UTC, vkurennov commented on spec/acceptance/best_answer_for_question_spec.rb
> +        sleep(4)
Великоваты паузы, обычно 2х сек более чем достаточно

2018-11-01 16:17 UTC, rublen commented on app/assets/javascripts/vote.js
> +  var voteUp = document.querySelector('.vote-up');
да, он не нужен, случайно остался

2018-11-01 16:19 UTC, rublen commented on app/assets/javascripts/vote.js
> +      if (upVoted == true) {
знаю

2018-11-01 16:36 UTC, rublen commented on app/controllers/concerns/voted.rb
> +      vote_id: vote.id,
тут не понятно, в роутах votes вложены в вопросы и ответы, но я для них указала опцию shallow: true, по-этому для экшина unvote(удаление голоса) роут такой:
unvote_vote       DELETE       /votes/:id/unvote(.:format)       votes#unvote
т.е. нужен только id голоса

2018-11-01 16:40 UTC, rublen commented on spec/acceptance/best_answer_for_question_spec.rb
>          within(all(".row").first) { expect(page).to have_content("#{answer_2}") }
как раз этот тест у меня самый проблемный)

2018-11-01 16:51 UTC, rublen commented on app/controllers/concerns/voted.rb
> +module Voted
Да, тоже думала, что смысл консернов не в этом, но мне так понравился мой "тонкий" контроллер, что решила оставить, посмотреть, что ты скажешь)
За публичные/приватные методы в консерне контроллера спасибо

2018-11-01 18:01 UTC, rublen commented on app/assets/javascripts/vote.js
> +      votes = JSON.parse(event.detail[2].responseText).votable_sum;
не понимаю
эксперимент:
      console.log('------------------------')
      console.log(event.detail)
      console.log('------------------------')
      console.log(event.detail[2])
      console.log('------------------------')
      console.log(event.detail[2].responseText)
      console.log('------------------------')
      console.log(event.detail[2].responseText['up_voted'])
      console.log(event.detail[2].responseText.up_voted)
      console.log(JSON.parse(event.detail[2].responseText).up_voted)

Результат:
![image](https://user-images.githubusercontent.com/16900457/47869931-e9e8ef00-de10-11e8-912c-67477c0b7fc5.png)

2018-11-01 18:07 UTC, rublen commented on spec/acceptance/best_answer_for_question_spec.rb
> +        sleep(4)
он и так не работает, что-то сламалось, надо смотреть

2018-11-01 18:29 UTC, rublen commented on app/models/concerns/votable.rb
> +    def vote(user)
agree

2018-11-02 04:32 UTC, rublen commented on app/views/votes/_voting.html.slim
> +  - elsif votable.downvoted?(current_user)
здесь тоже не знаю, как это можно сделать. Опишу схему для стрелки вверх, чтоб легче ориентироваться: 
у меня 3 таких стрелки (2 из них всегда спрятаны), назову их условно 
"unvote" - ссылка на удаление голоса, зеленая, чтобы показать пользователю, что уже проголовано в эту сторону
"upvote" - ссылка на голосование +1 голос
"span" - просто серая стрелка, как бы неработающая ссылка
Схема:
if upvoted?
  unvote
  upvote, hide
  span, hide
elsif downvoted?
  unvote, hide
  upvote, hide
  span
else
  unvote, hide, href="" (ошибка, если оставить ссылку, потому что голоса еще не существует)
  upvote
  span, hide

2018-11-02 08:18 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +      votes = JSON.parse(event.detail[2].responseText).votable_sum;
Ну а что лежит в detail[0] и detail[1]? Там же в detail массив из 3-х элементов, посмотри их  все, а не только 3й элемент (подсказка: из лога вижу, что распсрсенный json будет в 0м элементе)

2018-11-02 08:18 UTC, vkurennov commented on app/assets/javascripts/vote.js
> +      if (upVoted == true) {
ну а чего же не пишешь как надо? ))

2018-11-02 08:19 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      vote_id: vote.id,
я немножко про другое: если мы создали голос и возвращаем ответ, то как на клиенте понять за какой это именно объект голос, если на странице есть вопрос и ответ с одинаковым id?

2018-11-02 08:22 UTC, vkurennov commented on app/views/votes/_voting.html.slim
> +  - elsif votable.downvoted?(current_user)
А еще если ссылки отличаются только классами, можно писать что-то вроде:

```
- html_classes = upvoted?  ? 'classes for upvoted' : 'classes for downvoted'
= link_to octicon(...), upvote_path(...), class: html_classes
```

тогда у тебя ссылка будет одна и ты под условия вынесешь только атрибуты, на что я и намекал в комментарии

2018-11-02 08:22 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +module Voted
Да нет, можно не убирать, такой подход тоже вполне имеет право на жизнь, главное - не запутаться

2018-11-02 08:23 UTC, vkurennov commented on spec/acceptance/best_answer_for_question_spec.rb
>          within(all(".row").first) { expect(page).to have_content("#{answer_2}") }
ну вот и надо попробовать его переписать с меньшей привязкой к верстке

2018-11-02 08:23 UTC, vkurennov commented on spec/acceptance/best_answer_for_question_spec.rb
> +        sleep(4)
на ИЗ можем разобраться

2018-11-03 11:45 UTC, vkurennov approved these changes

2018-11-05 10:54 UTC, merged